### ISSUE TITLE
Traefik v2

### ISSUE THREAD

**Issue by regner** [linuxserver/Heimdall-Apps#118]
Just as a heads up, Traefik v2 removes the `/health` endpoint. They do still have a number of different metric providers. I believe all but the Prometheus one are push though. So if Traefik is to continue being an enhanced application it will probably need to support getting information from the Prometheus `/metrics` endpoint in Traefik.

**Comment by mvdkleijn** [comment]
@aptalca @KodeStar This issue can be close as it was already fixed by https://github.com/linuxserver/Heimdall-Apps/pull/125
