### ISSUE TITLE
qBitTorrent v4.2.0 requires API v2 endpoints

### ISSUE THREAD

**Issue by jeremysherriff** [linuxserver/Heimdall-Apps#146]
qBitTorrent enhanced app blade stops working after updating qBt to v4.2.0.

As per release notes here (https://www.qbittorrent.org/news.php) qBt v4.2.0 enforces modern API endpoints:
> WEBUI: Drop legacy WebAPI support (glassez)

I am creating a PR.

**Comment by k-matti** [comment]
#147 was merged but heimdall still does not works with qbittorrent 4.3.0.1
