### ISSUE TITLE
Creating Private Apps

### ISSUE THREAD

**Issue by nicoolaro** [linuxserver/Heimdall-Apps#175]
Wiki says:
Go to https://apps.heimdall.site, depending if the app you are creating is a foundation or enhanced app, go to the relevant section and download the Zip for any application (More actions).

I cant find neither Zip nor More actions.

**Comment by tomuky2k** [comment]
Hi, this has been open for 19 days, not sure if you have resolved your problem yet, but you do the following:
1) Go to https://apps.heimdall.site/
2) Search for any app, e.g. TYPO
3) Click 'More Actions' at the end of the bar for the app e.g. TYPO and download either the foundation or enhanced zip/template.
4) Using the zip you downloaded you can modify the files, as per the wiki instructions.

**Comment by nicoolaro** [comment]
Yep, thanks
