### ISSUE TITLE
provide GIF examples for enhanced apps

### ISSUE THREAD

**Issue by piramiday** [linuxserver/Heimdall-Apps#222]
in order to let users know right away **what is actually enhanced** about the enhanced apps, all the logos in the [enhanced app list page](https://apps.heimdall.site/applications/enhanced) should be dynamic, like previews.

for example, the small GIF for NZBGet in the main page is incredibly useful to understand its functionality:

![](https://heimdall.site/img/enhancedapp.gif)

ideally, this should be done for all the enhanced apps.

**Comment by aptalca** [comment]
Many of those are community submitted. Feel free to submit PRs with animated gifs

**Comment by piramiday** [comment]
yeah, sure, but I am barely being able to make it work for me as it is...

I am proposing this usability enhancement and opening up an issue for whomever might be able to do it.
it took me a while to understand what was actually being enhanced, here.

it might be worth to switch the "marketing name" from "enhanced apps" to something more intuitive, like "static" and "dynamic" app blocks, or something like that.
