### ISSUE TITLE
Read-only share

### ISSUE THREAD

**Issue by arcadiush** [linuxserver/Heimdall-Apps#289]
I would like to provide my users with a "desktop with links to websites" on the web for reading only without the possibility of editing the content.
If it is possible?

**Comment by mvdkleijn** [comment]
This issue should be in https://github.com/linuxserver/Heimdall as that is the appropriate place. Unfortunately, I do not seem to be able to transfer it myself.

This repository is only for apps and the applist in Heimdall, not Heimdall itself.

**Comment by mvdkleijn** [comment]
I'm closing this issue. (see my earlier comment) Feel free to re-open if needed.
