### ISSUE TITLE
Plex General error connecting with API

### ISSUE THREAD

**Issue by P6g9YHK6** [linuxserver/Heimdall-Apps#292]
getting a General error connecting with API
i tried every possible combination of url that i can to get it to work with no success,

**Comment by TheCatLady** [comment]
The Plex enhanced app is working for me.

Make sure you got the authentication token following the directions here: https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token/

(It is NOT the same as the Plex claim token, in case you made that mistake.)

**Comment by vercas** [comment]
Got this error as well, the problem was that Heimdall insists on using port 32400.  
I was using a different port to give access to my Plex server.  
Code's here: https://github.com/linuxserver/Heimdall-Apps/blob/master/Plex/Plex.php#L49

**Comment by P6g9YHK6** [comment]
> 
> 
> The Plex enhanced app is working for me.
> 
> Make sure you got the authentication token following the directions here: https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token/
> 
> (It is NOT the same as the Plex claim token, in case you made that mistake.)

I confirm that i have done it correctly.

**Comment by P6g9YHK6** [comment]
> 
> 
> Got this error as well, the problem was that Heimdall insists on using port 32400.
> I was using a different port to give access to my Plex server.
> Code's here: https://github.com/linuxserver/Heimdall-Apps/blob/master/Plex/Plex.php#L49

has said i tired everything: reverse proxy address, direct ip with and without port, nat loopback address no clue why it is not working.

**Comment by Yrlish** [comment]
I also have problem with the Plex config. After checking the code @vercas referred to it insists on using port 32400 and **not** using the `/web` path. Also my server requires HTTPS on 32400.

What I need to use: `https://hostname:32400/web/<endpoint>`
That the code seem to construct: `http://hostname:32400/<endpoint>`

**Comment by Aerya** [comment]
Hi, same here. SSL (it's 2021) and different port.

**Comment by Epirr** [comment]
Same issue here. My Plex port is manually set as 32400 I have the URL set as https://app.plex.tv/desktop which works fine. 

I followed this article to get my Plex token: https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token/

I entered it in and clicked the Test button, and after about 10-15 seconds a popup error came up saying "General error connecting with api"
