### ISSUE TITLE
Add Loxberry Application

### ISSUE THREAD

**Issue by Noschvie** [linuxserver/Heimdall-Apps#303]
https://github.com/mschlenstedt/Loxberry
Thanks!

**Comment by Noschvie** [comment]
https://github.com/christianTF/LB-Ressources/blob/master/Logos%202018-2/Logo%20und%20LoxBerry%20f%C3%BCr%20loxberryde.png

**Comment by Noschvie** [comment]
@dgibbs64 : maybe you can add this application and logo ? Thanks!

**Comment by dgibbs64** [comment]
I see you noticed I was busy last night 😄

**Comment by mvdkleijn** [comment]
Already in https://apps.heimdall.site/search?search=Loxberry
Closing issue.
