### ISSUE TITLE
ruTorrent - /RPC2 not found

### ISSUE THREAD

**Issue by DeSavanger** [linuxserver/Heimdall-Apps#428]
Hello,

When connecting to the ruTorrent Advanced Plugin, you will get an error 404 that `http(s)://YOURRUTORRENTURL/RPC2` isn't found. Please change the `/RPC2` in the `SupportedApps/ruTorrent/ruTorrent.php` to `/plugins/rpc/rpc.php` and the script will connect succesfully.

**Comment by kekZiger** [comment]
#734 

Can this be closed?
