### ISSUE TITLE
Stash - Logo Update

### ISSUE THREAD

**Issue by halorrr** [linuxserver/Heimdall-Apps#429]
The stash logo could use an update https://github.com/linuxserver/Heimdall-Apps/blob/master/Stash/stash.png

I've never seen that logo in the time I've been using the app and it is really low quality. 

The official SVG of the logo is https://stashapp.cc/images/stash.svg directly from their site https://stashapp.cc

![stash](https://user-images.githubusercontent.com/1358708/154772033-9a0d9f9e-55a5-48b4-ab33-baec9ab5951e.svg)

**Comment by KodeStar** [comment]
Then create a PR
