### ISSUE TITLE
Firefly III

### ISSUE THREAD

**Issue by arghyadipchak** [linuxserver/Heimdall-Apps#483]
Firefly III icon and description not being shown while adding.

![Screenshot from 2022-03-24 00-30-56](https://user-images.githubusercontent.com/32430374/159775932-50ff415e-d74f-4505-bfed-597195c35dbd.png)

**Comment by arghyadipchak** [comment]
This might help in debugging the problem.

![Screenshot from 2022-03-24 00-35-58](https://user-images.githubusercontent.com/32430374/159776972-1926d600-5a68-403d-8e54-d2fc13bc5204.png)

**Comment by KodeStar** [comment]
Should be fixed
