### ISSUE TITLE
htmlspecialchars() expects parameter 1 to be string

### ISSUE THREAD

**Issue by DougEdey** [linuxserver/Heimdall-Apps#497]
When editing AdGuardHome I get the following:

```
"htmlspecialchars() expects parameter 1 to be string, array given (View: /config/www/SupportedApps/AdGuardHome/config.blade.php) (View: /config/www/SupportedApps[ ▶]()"
```

I'm not sure if this is an issue in the apps files or the main app itself, but since the file that is causing the error is in this repo, I figured this is the best place to raise it.

Running Heimdall 2.4.11

**Comment by mvdkleijn** [comment]
Thanks for the report. I'm new here and working through the backlog of issues and PRs. I cannot reproduce on latest version. Closing. Feel free to re-open if needed.
