### ISSUE TITLE
Issue with Dash. integration

### ISSUE THREAD

**Issue by MauriceNino** [linuxserver/Heimdall-Apps#524]
Hello! I have created an integration to my project dash., which has been merged. Unfortunately, users reported that it did not work.

I have copied the output and created a PR according to your guidelines. As I can find not information on how to set up a local development environment to test the integration, I don't know how I could debug the problem. The only thing I can provide is that I tried it locally, and I get a 500 Internal Server Error when selecting Dash., but not when selecting any other application.

<img width="789" alt="image" src="https://user-images.githubusercontent.com/18658092/180001392-e1271633-6d32-4579-8564-e3a4b30b3c55.png">

One thing I think that could be the problem is the mismatch between the name and the folder path (Dash. Vs Dashdot). The actual name of the project is Dash. though.

**Comment by dgibbs64** [comment]
Thanks I will take a look

**Comment by dgibbs64** [comment]
renamed to Dashdot worked

**Comment by MauriceNino** [comment]
> The actual name of the project is Dash. though

@dgibbs64 Is it not possible to include a dot in the name?

**Comment by dgibbs64** [comment]
The dot seems to cause some issues. The php file would need to be called Dash..PHP for example. It might work but I'm not much of a PHP or laravel developer.

**Comment by MauriceNino** [comment]
Could you test it though? I don't know how to set up a dev environment for Heimdall and I would really like the integration to have the correct name.

**Comment by MauriceNino** [comment]
@dgibbs64
