### ISSUE TITLE
Ip public address review

### ISSUE THREAD

**Issue by barzag** [linuxserver/Heimdall-Apps#525]
Hello every one,

I would like to generate a APPS who return a public ip address.
For exemple to retrun "docker exec -it transmission curl ifconfig.io" in the Apps Transmission.
Do you have any idea ?

Thank's 👍

**Comment by mvdkleijn** [comment]
The request / suggestion is very unclear to me. Can you maybe re-phrase for better understanding?

**Comment by mvdkleijn** [comment]
Closing this to clean up, feel free to reopen or comment when needed.

Reasoning:
- unclear
- no additional info received
