### ISSUE TITLE
Plex enhanced app no longer works after SSL Verify Toggle was added

### ISSUE THREAD

**Issue by Dallas-J** [linuxserver/Heimdall-Apps#540]
For some background, I have only been using this app for about a week and have no history with or understanding of PHP.

That said, my Plex integration is not working. Other users have reported this in a discussion topic as well as on Reddit: 
* https://github.com/linuxserver/Heimdall/discussions/740
* https://www.reddit.com/r/homelab/comments/udsi8x/heimdall_enhanced_apps_broke/

All of my other integrations work just fine, and I am running Plex through a docker container with 'host' networking.

Reverting these commits fixes the issue:
* https://github.com/linuxserver/Heimdall-Apps/commit/8dc8d0dc206c570cde44bbbe1d1fecdb2a82f30f
* https://github.com/linuxserver/Heimdall-Apps/commit/0ecb64ec2849ddec3e4eb71f124020bf2d87538d (dependent on https://github.com/linuxserver/Heimdall-Apps/commit/8dc8d0dc206c570cde44bbbe1d1fecdb2a82f30f)

**Comment by dgibbs64** [comment]
Thanks for reporting this. I am not much of a PHP/Laravel person myself but I think this is an important one to fix.

**Comment by quotschmacher** [comment]
At least the "recent"-value isn't written anymore into the return results nad the "onDeck" is requested twice, first without regarding the TLS-option and then regarding the TLS option.
