### ISSUE TITLE
[Bug, Feedback] Creating an Private App seems not to function.

### ISSUE THREAD

**Issue by frudolph77** [linuxserver/Heimdall-Apps#541]
Hello,

I followed the instruction from [wiki/Creating-Private-Apps](https://github.com/linuxserver/Heimdall-Apps/wiki/Creating-Private-Apps). But nothing happens on my Heimdall installation. I can't add my private app on the `items/create` page. The app is neither available in the **Application Type** drop down nor on the text field stating **Application Name**. 

I'm running Heimdall with the official linuxserver Docker image. The reason for trying out these instructions is, that i wolud like to add apps to Heimdall.

Feedback:

It took me some time to get an working App, because there is one step missing in the wiki. 
It's mandatory to edit the appname.php too, and replace the previous appname by the new one, otherwise you will get this error. 

```
root@7d75a4538329:/var/www/localhost/heimdall# php artisan register:app Foo

In SupportedApps.php line 165:
                                                
  Class '\App\SupportedApps\Foo\Foo' not found  
```
After dealing with this it runs ok:
```
root@7d75a4538329:/var/www/localhost/heimdall# php artisan register:app Foo
Application Added - Foo - 201a6b3053cc1422d2c3670b62616221d2290929
```

Maybe you should state this in the wiki, or even better provide some templates inside the wiki.

I would have created a pull request but it's not possible for wikis.

After some further investigations, and looking into the sqlite db. I found out that my app was added to the `applications` table but without a SHA value. Nothing was inside in the `items` and `item_tag` tables. After adding the appropriate values to that tables I finally managed to add an private application. But I think that's not the way how it should work.

kind regards
Frank

**Comment by sammyke007** [comment]
How did you fix this please?
I've been wasting hours to try and add ann app, but it won't work. 

I have extracted the files in zigbeemqtt.zip to:
/opt/heimdall/www/SupportedApps/zigbeemqtt/

I have executed these commands:
`
docker exec -it heimdall bash
cd /var/www/localhost/heimdall
php artisan register:app zigbeemqtt
`

I get confirmation
`Application Added - zigbeemqtt - b2a1d91f32dc4d5bc979768320e0a689adf58d41
`

but it won't show up in the list on Heimdall!

**Comment by frudolph77** [comment]
This is quite hacky.

You need to edit the SQLite file of Heidall. It's `app.sqlite` in `/opt/heimdall/www/`. Open this file with an appropriate tool and edit tables mention above. The content of these tables is self explaining, if you have an app which is 'shipped' with Heimdall installed.

First add the entry to the `item` table

| id | title | colour | icon | url | skipped cols  | class  | appid | appdesc |
|----|------|-------------|---|---|---|---|---|---|
|next free number | My awesome App | color to use for the tag | icon shown in the tag | https:/my.awesome.app | ... | \<class from application table\>| \<appid from application table\> | My Awesome App is so cool |

then add in `item_tag`
| item_id | tag_id | created_at | updated_at |
|-|-|-|-|
| \<id of app from item table\> | 0 | | |

I hope this helps a little bit.

**Comment by sammyke007** [comment]
Ok tnx, any idea how I bypass this FOREIGN key error?

<img width="667" alt="image" src="https://user-images.githubusercontent.com/33524412/193036324-eb6a9dac-9b8a-4d70-8061-da92dac51ce8.png">

**Comment by frudolph77** [comment]
You've been using the false value for the item_id :-)

Yeah, it's not user friendly. 
I think it had work previously, but breaks after some updates. The code needs to be fixed so that these entries are created as well. 

It took me some hours to find this solution and I only found it because I've been curious about the contents of the sqlite file

**Comment by keriati** [comment]
I have been investigating this a bit and it seems the list for selecting apps is coming from the file `storage/app/supportedapps.json`. So to get your private App listed you also need to add it there in the directory `/var/www/localhost/heimdall/storage/app`

**Comment by keriati** [comment]
same issue reported here: https://github.com/linuxserver/Heimdall/issues/862
