### ISSUE TITLE
Syncthing app doesn't show any folder data

### ISSUE THREAD

**Issue by macbean101** [linuxserver/Heimdall-Apps#542]
I set up the syncthing enhanced app, put in the api key, and it all tested successfully.  But it shows 0 needed files/bytes at all times and doesn't indicate that there's 2 folders being synchronized.

**Comment by mvdkleijn** [comment]
Does this still happen on latest Heimdall after updating the app list through the UI?
If no, I'll close the issue.

**Comment by macbean101** [comment]
On my instance, after updating apps, I am still able to see files/size to be synchronized.

**Comment by mvdkleijn** [comment]
@macbean101 You're still **not** able to see number of files syncing... ok.

What version of Heimdall are you using?
Do you have any logs / errors for Heimdall?

**Comment by macbean101** [comment]
apologies, my phrasing was poor it seems.  the syncthing app in heimdall shows the correct status for syncthing and (from my perspective) this can be closed.

**Comment by mvdkleijn** [comment]
> apologies, my phrasing was poor it seems.  the app in heimdall shows the correct status for syncthing and (from my perspective) this can be closed. 

Ah thanks for clarifying and updating.
