### ISSUE TITLE
500 Server Error when saving Private Apps

### ISSUE THREAD

**Issue by koozma56** [linuxserver/Heimdall-Apps#554]
I'm getting 500 Server Error when saving trying to save Private Apps using Heimdall version  2.4.15  (even if it says 2.4.13).

Testapp was made by duplicating Pihole App and changing:
- Pihole.php -> Testapp.php (also changed Pihole to Testapp in two plaeces in this file)
- app.json (changed appid, name)

I've ran commands as per wiki for private apps. App is being listed in Application Type at the bottom of the list. Noticed that description is missing. Unable to save and getting 500 server error.

**Comment by keriati** [comment]
Please provide more details from the error, maybe from the laravel log at storage/logs/laravel-2022-11-12.log

**Comment by keriati** [comment]
Could be something like

    file_put_contents(/var/www/localhost/heimdall/storage/app/public/icons/testapp.png): failed to open stream: Permission denied

**Comment by keriati** [comment]
I submitted a fix above.

Workaround: select a different icon from your disk, don't use the default one.
