### ISSUE TITLE
Pi-Hole Live-Stats broken after updating AdminLTE

### ISSUE THREAD

**Issue by Mask3007** [linuxserver/Heimdall-Apps#579]
After Update Pi-Hole admin web interface the live-stats gone missing. 

In this Update Pihole added authentication to more endpoints. 

https://pi-hole.net/blog/2022/11/17/upcoming-changes-authentication-for-more-api-endpoints-required/

It seems that the pi-hole part is just calling the api.php endpoint without any queries. 

https://github.com/linuxserver/Heimdall-Apps/blob/master/Pihole/Pihole.php

To get it running again the endpoint should be called with the empty query `summaryRaw` and the api token in the query param `auth`. So the config-ui should also ask for the api key. In my setup I have following results:

HTTP 200 OK https://host/admin/api.php

`[]`

The correct endpoint should be.

https://host/admin/api.php?summaryRaw&auth=654065165cd1sa56d106c5115cd10as651d0652013rdc2dcas

HTTP 200 OK `{"domains_being_blocked":50123,"dns_queries_today":100123,"ads_blocked_today":80123,"ads_percentage_today":38.890179,"unique_domains":2123,"queries_forwarded":20123,"queries_cached":10123,"clients_ever_seen":20,"unique_clients":12,"dns_queries_all_types":100123,"reply_UNKNOWN":555,"reply_NODATA":5555,"reply_NXDOMAIN":999,"reply_CNAME":10123,"reply_IP":12312,"reply_DOMAIN":123,"reply_RRNAME":0,"reply_SERVFAIL":15,"reply_REFUSED":0,"reply_NOTIMP":0,"reply_OTHER":0,"reply_DNSSEC":0,"reply_NONE":0,"reply_BLOB":775,"dns_queries_all_replies":158602,"privacy_level":0,"status":"enabled","gravity_last_updated":{"file_exists":true,"absolute":1671730768,"relative":{"days":1,"hours":3,"minutes":35}}}`

I pseudomized the numbers :)

**Comment by antoniodourado** [comment]
I'm having the same issue. Waiting for the update.
Browser console is displaying the following and probably is for the same reason mentioned by @Mask3007 :
![image](https://user-images.githubusercontent.com/110608/209976668-43c7a81f-175f-4094-90a4-5f54ca002e5b.png)


Also, how do I update Heimdall to the latest version after it gets fixed? I'm runing it in a container with docker compose.

**Comment by tibbe** [comment]
I guess the new config UI needs to have a separate fields for the API token, so that Heimdall can correctly compose the URLs it needs (i.e. the URL field would still be the api.php base URL).

**Comment by wez** [comment]
FWIW, I worked around this by having my traefik proxy redirect the broken URL:

```yaml
middlewares:
    pihole-stats-redirect:
      # Workaround for https://github.com/linuxserver/Heimdall/issues/1083
      redirectRegex:
        regex: "^https://pihole.local/stats/api.php$"
        replacement: "https://pihole.local/admin/api.php?summaryRaw&auth=TOKEN"
```

and add `pihole-stats-redirect` to the list of middlewares for my pihole service.

I have the config URL explicitly set to `https://pihole.local/stats` in heimdall (which in turn implicitly appends `/api.php` when making the request).

This effectively allows unauthenticated access to just the stats page, via the proxy, which seems reasonable to me.

**Comment by rmatte** [comment]
I don't think that the config UI needs field for API token, because different apps could pass in the token with different names / identifiers for it. I just think it would be nice if the config field could accept a literal URL like...

http://172.17.0.4:80/admin/api.php?summary&auth=my_api_token

Where *my_api_token* is the token provided by pi-hole. That way the config field would be much more flexible. The field doesn't currently seem to allow for that.

**Comment by rmatte** [comment]
I'm also not really sure how this ended up with an enhancement label when the entire stats feature for pi-hole is effectively broken at this point. Just saying.

**Comment by keriati** [comment]
After triggering an Update of the App List it should be possible now to add Pi-hole with an api key.
Note: probably editing of the old Pi-hole entries will not work as they are now missing an api key from the db.

**Comment by Xaositek** [comment]
<img width="998" alt="image" src="https://user-images.githubusercontent.com/85509/211433898-2a07917c-f35c-401f-a41d-686876ab88f7.png">

Running Heimdall 2.5.5 within Docker on unRAID and after updating the Application list, I don't see the new API field yet.

<img width="469" alt="image" src="https://user-images.githubusercontent.com/85509/211434052-b421e118-d619-4a40-a030-a7235d226c39.png">

**Comment by keriati** [comment]
I would try to refresh the page, I dunno why, for me it just showed up at some point. Maybe some cache is keeping the old version...

**Comment by Xaositek** [comment]
> I would try to refresh the page, I dunno why, for me it just showed up at some point. Maybe some cache is keeping the old version...

At this point I've tried on my iPad, iPhone, MacBook, and Windows 11 VM. Tried Safari, Chrome, and Firefox. I don't think it's cache or browser at this point. I've also restarted the Docker container twice.

**Comment by rmatte** [comment]
> > I would try to refresh the page, I dunno why, for me it just showed up at some point. Maybe some cache is keeping the old version...
> 
> At this point I've tried on my iPad, iPhone, MacBook, and Windows 11 VM. Tried Safari, Chrome, and Firefox. I don't think it's cache or browser at this point. I've also restarted the Docker container twice.

For me I had to remove the Pi-hole app from heimdall and re-create it. They actually recommended doing that in a post / comment that I saw (I forget where).

**Comment by Xaositek** [comment]
> > > I would try to refresh the page, I dunno why, for me it just showed up at some point. Maybe some cache is keeping the old version...
> > 
> > 
> > At this point I've tried on my iPad, iPhone, MacBook, and Windows 11 VM. Tried Safari, Chrome, and Firefox. I don't think it's cache or browser at this point. I've also restarted the Docker container twice.
> 
> For me I had to remove the Pi-hole app from heimdall dashboard and re-create it. Not sure if you've done that or not but just mentioning it. Maybe your app list update didn't complete or something?

At this point I deleted my three links to different Pi-Hole servers I have, removed them from my trash bin, restarted the Docker container again, re-ran the Application list update and still nothing.

**Comment by Xaositek** [comment]
okay so just destroyed the entire Docker image and rebuilt it - problem is solved now.

**Comment by rmatte** [comment]
> I still can't figure out what URL to use. Since my docker container has the name "pihole" and runs on port 8081 I tried `http://pihole:8081/admin/api.php?summaryRaw&auth=<token>` and various other combinations of query parameters I could think of. What's the right URL to use?

When you're adding Pi-hole to heimdall make sure you have the application type selected as Pi-hole, then you'll have a "Config (Optional)" section at the bottom. Set the URL to http://<pi_hole_ip_address>:1010/admin/api.php and put the API key in the "API key" field right next to that. The main URL for actually visiting the Pi-hole page is configured above that Config section under the main URL field and should be set to http://<pi_hole_ip_address>/admin/login.php

**Comment by tibbe** [comment]
> > I still can't figure out what URL to use. Since my docker container has the name "pihole" and runs on port 8081 I tried `http://pihole:8081/admin/api.php?summaryRaw&auth=<token>` and various other combinations of query parameters I could think of. What's the right URL to use?
> 
> When you're adding Pi-hole to heimdall make sure you have the application type selected as Pi-hole, then you'll have a "Config (Optional)" section at the bottom. Set the URL to http://<pi_hole_ip_address>:<pihole_port>/admin/api.php and put the API key in the "API key" field right next to that. The main URL for actually visiting the Pi-hole page is configured above that Config section under the main URL field and should be set to http://<pi_hole_ip_address>:<pihole_port>/admin/login.php

Is the port 1010 different from the standard http port or do both urls have the same port?

**Comment by rmatte** [comment]
> > > I still can't figure out what URL to use. Since my docker container has the name "pihole" and runs on port 8081 I tried `http://pihole:8081/admin/api.php?summaryRaw&auth=<token>` and various other combinations of query parameters I could think of. What's the right URL to use?
> > 
> > 
> > When you're adding Pi-hole to heimdall make sure you have the application type selected as Pi-hole, then you'll have a "Config (Optional)" section at the bottom. Set the URL to http://<pi_hole_ip_address>:<pihole_port>/admin/api.php and put the API key in the "API key" field right next to that. The main URL for actually visiting the Pi-hole page is configured above that Config section under the main URL field and should be set to http://<pi_hole_ip_address>:<pihole_port>/admin/login.php
> 
> Is the port 1010 different from the standard http port or do both urls have the same port?

It entirely depends on how you set it up. I have mine running on port 1010 for the main http UI so that's what I use.

**Comment by tibbe** [comment]
Finally managed to make it work by using `http://pihole:80/admin/api.php`. Note that "pihole" is the container name and thus the name on the internal docker network. Port 80 is the *internal* container port of the docker container, not the port exposed on the host.
