### ISSUE TITLE
Request: Gitlab enhancement should offer different url for health-checks

### ISSUE THREAD

**Issue by spenceradolph** [linuxserver/Heimdall-Apps#598]
Similar to apps like proxmox or portainer, there should be an override URL to use the health check and api read. 

My personal use case:
The URLs I use in the top configuration are proxied with cloudflare access, so typically would have to login with my authentication provider before getting access to the application(s). This means that heimdall (currently) is unable to reach my gitlab instance through the url. But, since my heimdall is hosted in the same network as my other applications, the override url is simply the private IP and 'works'.

Possible Fix:
Add a URL field (similar to proxmox / portainer since I am familiar with them) which can override the application link at the top and use this url instead for the enhacement features.

Even cooler but harder fix (and probably not needed):
Add settings to give heimdall a cloudflare access token, and add those headers to all of its enhancement http requests.

**Comment by spenceradolph** [comment]
I was able to get around this limitation (for this and other sites) by starting the heimdall container with --add-host example.com:127.0.0.1.

See https://stackoverflow.com/questions/38302867/how-to-update-etc-hosts-file-in-docker-image-during-docker-build

**Comment by mvdkleijn** [comment]
So setting a custom URL for the API / enhancement features? Something like the Jellyfin enhanced app does sounds enough then.

Don't suppose you're up to making a PR?
