### ISSUE TITLE
Add this to `Image requirements` section on the wiki

### ISSUE THREAD

**Issue by hasecilu** [linuxserver/Heimdall-Apps#609]
It's odd to see the wiki without instructions using FOSS programs (¬.¬), so I wrote these instructions with the steps I did in my last 2 PR, so someone can find it useful.

Could someone add it to the wiki please?

---

## GIMP

- Open the `png` image and click on `Image > Crop to Content`, this will eliminate extra empty pixels around the logo.
- Then click on `Image > Scale Image...`, and select a size of 250x250 pixels approximately .

![Crop_content](https://user-images.githubusercontent.com/53124818/224453364-82753545-4b5a-4520-9bcc-f4476f0cf307.jpg)

## Inkscape

- Open the `svg` file and  remove all the unnecessary objects like the ones outside the work area, etc.
- Once finished click on `File > Save As...`, then in the dialog select `Optimized SVG (*.svg)`.
- Then in the `Optimized SVG Output` window select the checkmarks as shown below and click OK, the resultant SVG file should decrease in size about 30%-60%.

![Optimize_svg](https://user-images.githubusercontent.com/53124818/224454138-126c1b85-af7e-41c1-b71b-0cd066c63b1f.png)

**Comment by keriati** [comment]
thanks, added it.
