### ISSUE TITLE
Portainer widget shows no info

### ISSUE THREAD

**Issue by kroese** [linuxserver/Heimdall-Apps#625]
After I changed the IP of my portainer server, Heimdall will not display any info in the widget anymore.

I triple checked everything: I get the message "Succesfully communicated with the API" in Heimdall, if I change the username, I get "Invalid credentials". So the connection to Portainer is working. In Portainer itself I see all requests Heimdall makes, with "Succesfully authenticated" next to it, so it's 100 percent sure the calls arrive. I even verified I can connect to port 9000 via netcat inside the Heimdall container.

So everything seems perfectly fine, still the widget displays no info at all.

**Comment by keriati** [comment]
@kroese i recommend turning on debug mode in the .env file and checking the browser developer tools -> network tab for errors.

If it worked before the ip change, i would guess some configuration was not updated.
