### ISSUE TITLE
Add App to a docker image

### ISSUE THREAD

**Issue by marcolino7** [linuxserver/Heimdall-Apps#630]
Hi,
I am new and I would like to know how to add a just created App from here:
https://apps.heimdall.site/request/list

to a doker image of heimdall

Thanks

**Comment by mvdkleijn** [comment]
You should be able to (roughly) follow this guide: https://github.com/linuxserver/Heimdall-Apps/wiki/Creating-Private-Apps

There is no guide to adding apps from the requested list as far as I know.

**Comment by mvdkleijn** [comment]
Actually, you cannot download a working app from that site. That site is intended only for developers to download a template to **start implementing** a requested app. I.e. they don't exist yet.

Once an app exists, it will be available if you update the app list in the Heimdall UI.

Sorry for the wild goose chase. Closing this issue, feel free to re-open.
