### ISSUE TITLE
Issue with Tautulli Displaying Zero Streams Despite Active Playback

### ISSUE THREAD

**Issue by xxcriticxx** [linuxserver/Heimdall-Apps#650]
My Tautulli consistently displays zero streams even when there are active streams playing. Heimdall has effectively communicated with the API, as confirmed by the test. What steps can I take to resolve this issue?

Heimdall v 2.5.6
Tautulli v 2.13.1

**Comment by mvdkleijn** [comment]
Closing this to clean up, feel free to reopen or comment when needed.

Reasoning:
- no further information received
