### ISSUE TITLE
Call API openmediavault is broken

### ISSUE THREAD

**Issue by acalisesi** [linuxserver/Heimdall-Apps#651]
There is an error for the call API of openmediavault.

This is my error log:
[2023-08-28 08:38:01] local.ERROR: Undefined property: stdClass::$cpuUsage {"userId":1,"exception":"[object] (ErrorException(code: 0): 
Undefined property: stdClass::$cpuUsage at /config/www/SupportedApps/openmediavault/openmediavault.php:82) 

Openemdiavault changed the response for cpu usage:
https://github.com/openmediavault/openmediavault/commit/cf66f4c8bd44bb3bbd72cac361632135e338ba70

Can you fix it?
Thanks,
Andrea

**Comment by mvdkleijn** [comment]
Fix merged, closing issue.
