### ISSUE TITLE
[Paperless-ngx] Add Number of Documents in Inbox

### ISSUE THREAD

**Issue by nortecc** [linuxserver/Heimdall-Apps#658]
In the Paperless-ngx app, the number of documents in the inbox should also be displayed in addition to the total number of documents.

![image](https://github.com/linuxserver/Heimdall-Apps/assets/2800121/a03d92e5-f2a6-4b82-950e-144cc53e065c).

Therfore to `livestats.blade.php`  I added
```
<li>
        <span class="title">Inbox</span>
        <strong>{!! $documentsInbox !!}</strong>
</li>
```
and in `PaperlessNgx.php` I changed `livestats()` as follows:

```
	public function livestats()
	{
		$status = "inactive";
		$data = [];
		$attrs = $this->getRequestAttrs();

		$documents = json_decode(
			parent::execute($this->url("statistics"), $attrs)->getBody()
		);

		$data = [
			"documentCount" => $documents->documents_total ?? 0,
			"documentsInbox" => $documents->documents_inbox ?? 0
		];

		return parent::getLiveStats($status, $data);
	}```
A little quick and dirty but it works!

**Comment by ElJaeger** [comment]
Great enhancement! I think inbox is even more important than total documents.

**Comment by mvdkleijn** [comment]
It'd be even better if this was a pull request. :smile:

**Comment by mvdkleijn** [comment]
**bump** @nortecc If you feel up to it, I'd be happy to look at any PR.

**Comment by listiges-kaenguru** [comment]
I could create a PR but not test it because I am not using Paperless-ngx. What do you say?

**Comment by mvdkleijn** [comment]
@listiges-kaenguru I have paperless-ngx so I can probably test this. So: go for it 😄
