### ISSUE TITLE
Request: [uptime kuma] Include uptime kuma in enhanced app to display number monitors up and down

### ISSUE THREAD

**Issue by navilg** [linuxserver/Heimdall-Apps#666]
Enhance uptime kuma from foundation app to enhanced app with feature to display number of monitors which are UP and DOWN.

**Comment by imnotjames** [comment]
added in #706 cause I'm using it and it's helpful to have

![Screenshot 2024-02-28 at 03-54-49 Heimdall](https://github.com/linuxserver/Heimdall-Apps/assets/1551593/f38607b9-8f88-400a-bc08-011d4f8ca34c)

**Comment by navilg** [comment]
Thanks

**Comment by Noschvie** [comment]
Hello
Where is the polling interval coded for the Uptime-Kuma metrics end point?
Thanks

**Comment by Noschvie** [comment]
It' working well. Thanks!
I just want to know how often Heimdall core checks these values ?
Maybe someone can link the code line.

**Comment by navilg** [comment]
Heimdall doesnot poll the metrics on interval. It only polls when Heimdall page is loaded first time or the page is refeshed.

**Comment by imnotjames** [comment]
Yeah, I think that's general for all Heimdall apps.

You can probably open an issue on Heimdall core if you'd like to learn more about that.

https://github.com/linuxserver/Heimdall/blob/2.x/resources/assets/js/liveStatRefresh.js

It looks like there's a 30s refresh if it's inactive and 5s if "active" - which for uptime kuma, is if there's a down monitor

**Comment by Noschvie** [comment]
Thanks!

**Comment by mvdkleijn** [comment]
I see the answers are already nicely given, for which my thanks.

Please close this issue if your questions were answered.

My two cents by the way:

the intention of the stats on Heimdall apps is not really to provide a live view but to provide a convenient overview.

If you really need a fast, regular update have Uptime Kuma open directly would be a better option.

Also connecting Uptime Kuma's notifications to Telegram for example works quite nicely.
