### ISSUE TITLE
Jellyfin X-Media-Browser Header to be Deprecated

### ISSUE THREAD

**Issue by ProfDoof** [linuxserver/Heimdall-Apps#669]
https://github.com/linuxserver/Heimdall-Apps/blob/d0c189ebf9020b86b5a380464758354167987027/Jellyfin/Jellyfin.php#L44

According to this gist by one of the contributors on Jellyfin, this particular Header is going to be deprecated.

https://gist.github.com/nielsvanvelzen/ea047d9028f676185832e51ffaf12a6f

This may be something to discuss further with them though.

**Comment by mvdkleijn** [comment]
Interesting. Is that already live in the latest versions?

**Comment by ProfDoof** [comment]
Not yet. They still support it for now. Like I said though, probably something to discuss directly with them if you guys have any connections. I know no one and just came across it when I was doing other things. XD

**Comment by mvdkleijn** [comment]
OK, thanks for the info anyway @ProfDoof 
I don't think we have any direct connection to them (I don't anyway :smile:) as most of the "Enhanced Apps" in Heimdall are created by the Heimdall community, Jellyfin included I believe.

I'll leave this issue open for now. Anyone reading this and feeling like it, feel free to pick it up and connect with Jellyfin.

**Comment by mvdkleijn** [comment]
keep it active
