### ISSUE TITLE
[FEAT] - Multi-Language description

### ISSUE THREAD

**Issue by listiges-kaenguru** [linuxserver/Heimdall-Apps#719]
Heimdall itself ist multilingual. I would love to have templates for multilingual app.json files so that Heimdall shows the description in the set up language.

I would translate some descriptions if it is working.

By myself I am not skilled enough to make a start with this modification.

**Comment by mvdkleijn** [comment]
@listiges-kaenguru This definitely belongs in the main Heimdall repo, not here. Please move it there or create a new one there and close this.

This repo (Heimdall-Apps) is just a set of apps created by the community for the community.

**Comment by listiges-kaenguru** [comment]
done
