### ISSUE TITLE
[BUG] - 502 Bad Gateway - nginx/.1.24.0

### ISSUE THREAD

**Issue by WildStar2022** [linuxserver/Heimdall-Apps#720]
**Describe the bug**
The latest version is giving me a "502 Bad Gateway" nginx/1.24.0 error.

**To Reproduce**
n/a

**Expected behavior**
n/a

**Screenshots**
n/a

**Version info (please complete the following information):**
 - Heimdall:   image: linuxserver/heimdall:latest
 - Docker version (running under MicroK8s version of Kubernetes)

**Additional context**
n/a

- Not getting the "Bad Gateway" error with this:   image: linuxserver/heimdall:V2.5.8-ls251

**Comment by j0nnymoe** [comment]
1) this is the wrong repo
2) our smoke test of the container is booting fine : https://ci-tests.linuxserver.io/linuxserver/heimdall/latest/index.html so likely related to your k8s setup.
