### ISSUE TITLE
[BUG] - Duplicati enhanced does not work if set no password at duplicati

### ISSUE THREAD

**Issue by MEL1H** [linuxserver/Heimdall-Apps#727]
**Describe the bug**
Duplicati enhanced add works smooth if I set password at duplicati. However, I want to use it without password. When I set it no password, I also change widget settings at heimdall with no password. Still it does not get data from duplicati. If I click widget, it opens page without any proble.=m.

**To Reproduce**
1. Go to duplicati. Set it no password from settings.
2. Go back heimdall widget settings.
3. Set it enhanced on and make it without any password.
4. See error no communication.

**Expected behavior**
Get data from duplicati like with password setup.

**Version info (please complete the following information):**
 - Heimdall:  2.6.1
 - Raspberry pi 5, raspi os ,aarch64.
 - Duplicati version 2.0.7.1_beta_2023-05-25

**Comment by MEL1H** [comment]
I can share messages that heimdall returns when I set password on duplicati and heimdall and no password at heimdall and also no password at duplicati.

![Screenshot_20240408_182221_Chrome](https://github.com/linuxserver/Heimdall-Apps/assets/79664791/7cf8d939-a1af-42d3-874c-c41dade759a0)
![Screenshot_20240408_182058_Chrome](https://github.com/linuxserver/Heimdall-Apps/assets/79664791/256feddc-206d-4b4c-a74a-77c353afccc1)

**Comment by mvdkleijn** [comment]
Yeah that makes sense. The Heimdall app *always* tries to authenticate. I'll fix it a little later today.

**Comment by mvdkleijn** [comment]
@MEL1H Can you try the code change at #729 locally to see if that works for you? No guarantees though 'cause I don't have a Duplicati server to test against.

**Comment by MEL1H** [comment]
Still same and this is the message when I try to test it on app setting page.

![image](https://github.com/linuxserver/Heimdall-Apps/assets/79664791/20a759d9-c7a2-4b26-ae71-f456282dc96a)

**Comment by mvdkleijn** [comment]
Did you apply the code changes I pointed you to? Did you empty the password field in the config?

**Comment by MEL1H** [comment]
Yes. But now I am done with duplicati. Thank you for your support
