### ISSUE TITLE
[BUG] - Nextcloud app authentication does not work

### ISSUE THREAD

**Issue by k-matti** [linuxserver/Heimdall-Apps#770]
**Describe the bug**
![image](https://github.com/user-attachments/assets/1d7bce98-84c9-4662-9ca0-19cef67bfca0)

I have created app password but heimdall can't connect to my nextcloud instance

**Comment by mvdkleijn** [comment]
PRs welcome. I have limited time available for this repository so I prefer to spend it approving PRs. Especially considering this is kinda a community effort. (adding and maintaining apps)

**Comment by iamdoubz** [comment]
You have to add your self signed certificate to your "cacerts" file. If you are using Ubuntu, you can follow this [guide](https://superuser.com/a/383466).

You can also modify the `ItemController.php` file near line 225 to include the ssl option of "cafile" as described in [this post](https://stackoverflow.com/a/28701786).
