### ISSUE TITLE
[BUG] - ArchiSteamFarm fails to authenticate

### ISSUE THREAD

**Issue by JoshuaVandaele** [linuxserver/Heimdall-Apps#773]
**Describe the bug**
My password contains special characters such as `*`, `!`, `^`, `@`, `%`, ..., which the current implementation makes ArchiSteamFarm return 401.

**To Reproduce**
1. Go add a config for ArchiSteamFarm with the correct URL and password, which contains special characters
2. Click on "Test"
3. See error

**Expected behavior**
A successfully established connection

**Version info (please complete the following information):**
 - Heimdall: 2.6.1
 - Docker, if applicable: lscr.io/linuxserver/heimdall:latest
 - App: ArchiSteamFarm
 - Version of remote application App tries to use: 6.0.6.4

**Additional context**
This is fixable by using the [Authentication header](https://github.com/JustArchiNET/ArchiSteamFarm/wiki/IPC#authentication) instead of putting the password in the URL, this [issue already happened to me in the past](https://github.com/C4illin/ASFclaim/issues/35).

**Comment by JoshuaVandaele** [comment]
This is still an issue

**Comment by PedroBuffon** [comment]
ArchiSteamFarm on $this->config->password doesn't urlencode the password so it passes like p@ssword with the special character on the url itself, which is a big problem, i've never used ArchiSteamFarm, but i can make a quick fix adding a urlencode($this->config->password) to the code parts.

**Comment by PedroBuffon** [comment]
PR made, now just wait for the merge and test it out.
