### ISSUE TITLE
[BUG] - Emby app is not working anymore

### ISSUE THREAD

**Issue by k-matti** [linuxserver/Heimdall-Apps#801]
I have generated a token but seems like Heimdall can't connect to Emby's API;

![obraz](https://github.com/user-attachments/assets/098eb273-647a-4bce-9045-0c7202e1a6bd)

**Comment by mvdkleijn** [comment]
Did it work before with your setup? The error 403 suggests that you're forbidden from using Emby.

**Comment by TheGameProfi** [comment]
What Emby and Heimdall version are you Using?
For me it's working with the newest Version and the Beta Release
